### ISSUE TITLE
Инстансы json

### ISSUE THREAD

**Issue by roman-bodavskiy** [Little-Pie/repeater-botya#1]
https://github.com/Little-Pie/repeater-botya/blob/db220376d1e9c5987580817a721d52060f146052/src/Config.hs#L22

Привет! Меня зовут Роман, начал ревьюить твоего бота
В этом месте можно использовать дерайвинг вместо ручного инстанса (и в некоторых других местах)
И кстати поля немного не соответсвуют тому, что в шаблоне

**Comment by roman-bodavskiy** [comment]
https://github.com/Little-Pie/repeater-botya/blob/db220376d1e9c5987580817a721d52060f146052/src/Config.hs#L36-L42

вот это можно упростить
```
getConfig :: IO (Maybe Config)
getConfig = do
  rawJSON <- B.readFile "config.json"
  pure $ decodeStrict rawJSON
```

**Comment by Little-Pie** [comment]
Привет, пыталась добавить тебя как ревьюера в пул реквест, но почему-то не работает
