### ISSUE TITLE
Описание проекта

### ISSUE THREAD

**Issue by pavelzarubin** [Little-Pie/repeater-botya#10]
Не хватает инструкции для запуска бота.

**Comment by Little-Pie** [comment]
Этого недостаточно?
https://github.com/Little-Pie/repeater-botya#installation
Надо добавить что-то про stack run?

**Comment by pavelzarubin** [comment]
Ну да, представь что пишешь для человека, который вообще с программированием не знаком. А среди заказчиков такие часто попадаются.
