### ISSUE TITLE
QueryItem

### ISSUE THREAD

**Issue by pavelzarubin** [Little-Pie/repeater-botya#12]
```haskell
getUpdates :: Int -> App BS.ByteString
getUpdates offset = do
  Environment {..} <- ask
  response <- liftIO $ httpBS $ setRequestResponseTimeout (ResponseTimeoutMicro $ (timeout + 1) * 1000000) $ parseRequestThrow_ $ "https://api.telegram.org/bot" ++ token ++ "/getUpdates?offset=" ++ show offset ++ "&timeout=" ++ show timeout
  pure (getResponseBody response)
```
Почему бы вместо конкатенции не использовать ```QueryItem```, которые и созданы для параметров запроса?

**Comment by Little-Pie** [comment]
Мне кажется, теперь запрос выглядит громоздким и менее понятным....

**Comment by pavelzarubin** [comment]
На мой взгляд, выглядит лучше, так как ты отделила адрес с методом от параметров метода. К тому же всегда можно напутать с символами для указания параметров, а тут параметры передаются так как надо.
