### ISSUE TITLE
Структура кода

### ISSUE THREAD

**Issue by roman-bodavskiy** [Little-Pie/repeater-botya#2]
https://github.com/Little-Pie/repeater-botya/blob/db220376d1e9c5987580817a721d52060f146052/src/Handle.hs#L14-L31

слишком большая вложенность кода

**Comment by roman-bodavskiy** [comment]
В модуле TelegramBot дублируется логика 

```
  case userMessages of
    [] -> pure (SendMsgsResult (UpdateId 0) chatIdsForRepeat repeatNumbersList)
    [userMsg] -> do <логика>
   (userMsg : userMsgs) -> do <та же самая логика>
```

Или она чем-то отличается?
Здесь будет правильней избавиться от рекурсии с помощью функции forM:

```
forM userMessages $ \userMessage -> do
    <логика>
```

Логику обработки одного апдейта можно вынести в отдельную функцию

**Comment by Little-Pie** [comment]
Я исправила sendMsgs через foldM, стало меньше кудо и не дублируется. Так пойдет?

**Comment by roman-bodavskiy** [comment]
да, мне кажется так лучше
