### ISSUE TITLE
Использование newtype

### ISSUE THREAD

**Issue by roman-bodavskiy** [Little-Pie/repeater-botya#4]
Вот эти кортежи с Int выглядят довольно странно и запутанно

```
type RepeatNumbers = [(Int, Int)]
sendMsgs :: TelegramUpdates -> [Int] -> RepeatNumbers -> App (Int, [Int], RepeatNumbers)
```

Я предлагаю, вместо Int использовать ньютайпы, например
`newtype ChatId = ChatId Int`
Вместо длинных кортежей можно использовать АДТ. Может иногда имеет смысл использовать Map (когда нужно делать lookup по ключу)

**Comment by Little-Pie** [comment]
Я сделала синонимы типов, чтобы были понятнее типы у функций. Такая же была цель? Мне показалось, если писать newtype, то придется слишком много раз писать сами конструкторы. Или может зачем-то нужно было написать newtype? Можешь объяснить, пожалуйста.
Кортеж из 3 элементов уже длинный и его надо заменить АДТ?

**Comment by pavelzarubin** [comment]
> Я сделала синонимы типов, чтобы были понятнее типы у функций. Такая же была цель? Мне показалось, если писать newtype, то придется слишком много раз писать сами конструкторы. Или может зачем-то нужно было написать newtype? Можешь объяснить, пожалуйста. Кортеж из 3 элементов уже длинный и его надо заменить АДТ?

```newtype``` это та конструкция, которая нам позволяет создавать синонимы с разным поведением. Ну например у тебя есть ```ChatId``` и ```RepeatNum```. Если это будут обычные синонимы, то ты спокойно сможешь сложить эти два числа, и компилятор тебе ни слова не скажет, так как с его точки зрения, это не будет ошибкой. А если ты сделаешь ```newtype```, то такой проблемы не возникнет, так как это ```newtype```. К тому же, если не хочешь писать много раз конструкторы для синонимов ```Int```, можно сделать ```deriving Num```. По поводу кортежа, лучше создать ADT даже для пары, так как тип куда лучше объясняет зачем он нужен.
[Статья](https://habr.com/ru/post/323526/) про ```newtype```

**Comment by roman-bodavskiy** [comment]
> Кортеж из 3 элементов уже длинный и его надо заменить АДТ?

Вообще да, кортеж из трех элементов уже считается слишком длинным, особенно если там внутри одинаковый тип Int, который при этом имеет разный смысл. В твоем случае, `RepeatNumber` это тоже кортеж, и получается что-то типа 

`App (Int, [Int], [(Int, Int)])`

**Comment by roman-bodavskiy** [comment]
`(RepeatNumbersList ((chatId, read str :: Int) : filter (\a -> fst a /= chatId) repeatNumbers))`

Здесь похоже нужно использовать не список кортежей `[(ChatId, RepeatNumber)],` а `Map ChatId RepeatNumber` и функцию `Map.insert`, но раз уж библиотеки использовать нельзя, то пусть будет так

`read` это нетотальная функция. В проекте их запрещено использовать, лучше использовать `readMaybe` или `readEither`, и записывать в лог ошибку, в случае, если распарсить не получилось

**Comment by pavelzarubin** [comment]
> Здесь похоже нужно использовать не список кортежей `[(ChatId, RepeatNumber)],` а `Map ChatId RepeatNumber` и функцию `Map.insert`, но раз уж библиотеки использовать нельзя, то пусть будет так

`Map` использовать можно.

**Comment by roman-bodavskiy** [comment]
Да, я ошибся. Вот список библиотек стандартной поставки, которые можно использовать https://coda.io/@metalamp/education/haskell-platform-20
Так что лучше переделать на Map
